// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/shop_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShopManagementServiceClient is the client API for ShopManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopManagementServiceClient interface {
	//unary services
	GenerateBill(ctx context.Context, in *BillRequest, opts ...grpc.CallOption) (*BillResponse, error)
}

type shopManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopManagementServiceClient(cc grpc.ClientConnInterface) ShopManagementServiceClient {
	return &shopManagementServiceClient{cc}
}

func (c *shopManagementServiceClient) GenerateBill(ctx context.Context, in *BillRequest, opts ...grpc.CallOption) (*BillResponse, error) {
	out := new(BillResponse)
	err := c.cc.Invoke(ctx, "/proto.shopManagementService/GenerateBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopManagementServiceServer is the server API for ShopManagementService service.
// All implementations must embed UnimplementedShopManagementServiceServer
// for forward compatibility
type ShopManagementServiceServer interface {
	//unary services
	GenerateBill(context.Context, *BillRequest) (*BillResponse, error)
	mustEmbedUnimplementedShopManagementServiceServer()
}

// UnimplementedShopManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShopManagementServiceServer struct {
}

func (UnimplementedShopManagementServiceServer) GenerateBill(context.Context, *BillRequest) (*BillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateBill not implemented")
}
func (UnimplementedShopManagementServiceServer) mustEmbedUnimplementedShopManagementServiceServer() {}

// UnsafeShopManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopManagementServiceServer will
// result in compilation errors.
type UnsafeShopManagementServiceServer interface {
	mustEmbedUnimplementedShopManagementServiceServer()
}

func RegisterShopManagementServiceServer(s grpc.ServiceRegistrar, srv ShopManagementServiceServer) {
	s.RegisterService(&ShopManagementService_ServiceDesc, srv)
}

func _ShopManagementService_GenerateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopManagementServiceServer).GenerateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.shopManagementService/GenerateBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopManagementServiceServer).GenerateBill(ctx, req.(*BillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopManagementService_ServiceDesc is the grpc.ServiceDesc for ShopManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.shopManagementService",
	HandlerType: (*ShopManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateBill",
			Handler:    _ShopManagementService_GenerateBill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/shop_service.proto",
}
